# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" , "dev"]
  pull_request:
    branches: [ "main" , "dev"]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    env:
      DISPLAY: :0
  
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install mesa and patchelf
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y \
            libgl1-mesa-dev \
            libgl1-mesa-glx \
            libglew-dev \
            libosmesa6-dev \
            software-properties-common
        sudo apt-get install -y patchelf
        sudo apt-get install -y xvfb x11-xserver-utils
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24                
#     - name: Check if EGL library exists
#       run: ldconfig -p | grep EGL
#     - name: Check if libstdc library exists
#       run: ldconfig -p | grep  libstdc++
    - name: Enable Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        auto-activate-base: false
    - name: Test Conda
      run: |
          conda info
          CONDA_DEFAULT_ENV=test_myosuite
          conda create --name $CONDA_DEFAULT_ENV python=3.7.1 -y
          conda activate $CONDA_DEFAULT_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Run MuJoCo Rendering test
      run: python -m mujoco.render_test
    - name: Run Test environment
      run: |
        python -m myosuite.tests.test_myo
    - name: Install ffmpeg
      run: |
        sudo apt-get install --no-install-recommends ffmpeg && pip install ffmpeg scikit-video
    #   conda install -c conda-forge libstdcxx-ng
    #   export MUJOCO_GL=egl
    #   sudo apt-get install libx11-dev libglfw3-dev        
    #   export DISPLAY=:1
    #   pip install glfw
    # - name: Setup for screen rendering
    #   run: |
    #     export DISPLAY=:0
    - name: Test rendering
      run: python -m myosuite.utils.examine_env -e myoElbowPose1D6MRandom-v0 -r offscreen -n 1
    - name: Run Test jupyter-notebooks tutorials
      run: |
        source myosuite/tests/test_tutorials.sh
